### ISSUE TITLE
Update documentation for running scraper locally

### ISSUE THREAD

**Issue by Zohair-coder** [Zohair-coder/drexel-scraper#100]
Merge request #93 introduced some changes that break the usage documentation in the `README.md`. To scrape, users will need to define 3 environment variables before running the script:

```
DREXEL_USERNAME
DREXEL_PASSWORD
DREXEL_MFA_SECRET_KEY
```

Update the documentation to ensure users can use the scraper. Explaining the username and password variable should be fairly straightforward, but explaining how to obtain the MFA secret key is going to take a paragraph or two. In short, users would need to add a new 2FA method that uses a token generation app and instead of scanning a QR code to register a new application to add the login to the 2FA app, users would need to click the "Show secret key" or similar option and enter that in instead. They'd also probably need to verify their key is working, which might require them to run a script.

This task isn't as straightforward as it sounds and is still important. I would appreciate someone doing this for me.

**Comment by Zohair-coder** [comment]
Also it'll be nice if the user doesn't have the necessary environment variables defined, instead of throwing a generic exception that says they're not accessible, an error message with a link pointing them to the documentation for defining these environment variables would be awesome.

**Comment by sylvieed** [comment]
Hey @Zohair-coder I can help out with this issue. 

I also found a different way to get through the Drexel 2FA. On my account I have it text me a verification code every time I need to log in rather than using a token generation app. For this login method, I modified the source code to prompt for the code after it's sent rather than taking it from the environment variable. 

I don't know which sign in method is more popular, but I can add a config option for which one they use, support both, and document both as requested.

**Comment by Zohair-coder** [comment]
Hey @sylvieed, thanks for the initiative to tackle this task.

I think this is a good idea. The reason why I chose the secret key route is because the script runs as a cronjob (a recurring job - more info [here](https://www.freecodecamp.org/news/cron-jobs-in-linux/)) every 20 minutes on a server. I needed a fully automated way of logging into Drexel One for this cronjob.

But I think adding a secret key might be a big ask for new developers who want to contribute to the project. I think they'd rather just provide their username and password, and confirm access via the Authenticator app/SMS (or whatever app they use for 2FA) manually. This should be fine for development purposes.

We should support both methods of authentication: the devs can either provide the secret key environment variable, in which case this method of authentication will be prioritized, or they can choose to ignore the secret key environment variable, and they'd have to manually approve the login attempt.

 I think for regular contributors to the project, devs would prefer to set the secret key environment variable so that they don't have to manually confirm the login attempt every time they run the scraper. However, new devs who are just checking out the project might find your approach simpler.

Thanks again for your input :)
